name: rag_app
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python
  - python=3.11
  
  # Core ML packages (conda handles these better)
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn=1.7.2
  - numpy=1.26.4
  - pandas=2.2.0
  
  # Core packages available in conda
  - pip
  - requests=2.32.5
  - pyyaml=6.0.3
  - tqdm=4.67.1
  - watchdog=6.0.0
  - pillow=11.3.0
  - boto3=1.40.58
  - plotly=6.3.1
  - nltk=3.9.2
  - tabulate=0.9.0
  
  # All other packages via pip (not available in conda)
  - pip:
    # FastAPI Backend
    - fastapi==0.120.0
    - uvicorn[standard]==0.38.0
    - pydantic==2.12.3
    
    # UI
    - streamlit==1.50.0
    - streamlit-authenticator==0.4.2
    - pydeck==0.9.1
    
    # Document Processing
    - PyMuPDF==1.26.5
    - reportlab==4.4.4
    - openpyxl==3.1.5
    - python-docx==1.2.0
    - python-dotenv==1.1.1
    
    # Utilities
    - rank-bm25==0.2.2
    - symspellpy==6.9.0
    - anthropic==0.71.0
    
    # OpenAI with compatible version
    - openai>=1.108.1,<2.0
    
    # LlamaIndex packages
    - llama-index==0.14.5
    - llama-index-core==0.14.5
    - llama-index-embeddings-huggingface==0.6.1
    - llama-index-llms-huggingface==0.6.1
    - llama-index-readers-file==0.5.4
    
    # Transformers ecosystem
    - transformers==4.57.1
    - sentence-transformers==5.1.2
    - accelerate==1.11.0
    - huggingface-hub==0.36.0
    - safetensors==0.6.2