name: rag_app
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python
  - python=3.11
  
  # Core ML packages (conda handles these better)
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn=1.7.2
  - numpy=1.26.4
  - pandas=2.2.0
  
  # Conda packages
  - pip
  - requests=2.32.5
  - pyyaml=6.0.3
  - tqdm=4.67.1
  - watchdog=6.0.0
  - pillow=11.3.0
  - boto3=1.40.58
  
  # Minimal pip packages to avoid conflicts
  - pip:
    # Core packages only
    - fastapi==0.120.0
    - uvicorn[standard]==0.38.0
    - pydantic==2.12.3
    - streamlit==1.50.0
    - streamlit-authenticator==0.4.2
    - plotly==6.3.1
    - PyMuPDF==1.26.5
    - reportlab==4.4.4
    - openpyxl==3.1.5
    - python-docx==1.2.0
    - python-dotenv==1.1.1
    - nltk==3.9.2
    - rank-bm25==0.2.2
    - symspellpy==6.9.0
    - tabulate==0.9.0
    - anthropic==0.71.0
