# User Authentication Configuration
# Passwords are hashed with SHA-256
# To generate a new user:
#   1. Use Python: hashlib.sha256(("password" + "salt").encode()).hexdigest()
#   2. Or use the admin panel (coming soon)

credentials:
  usernames:
    # Default admin account
    # Username: admin, Password: admin123
    admin:
      email: admin@arrowsystems.com
      name: Administrator
      password: 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
      salt: arrow_secure_2024
      role: admin
      
    # Example technician account
    # Username: tech1, Password: tech123
    tech1:
      email: tech1@arrowsystems.com
      name: John Smith
      password: 3d8e577bddb17db339eae0b3d9bcf78f62f8b7b9c8e34ca7eb7e9b8d8e9e5a94
      salt: arrow_secure_2024
      role: technician
      
    # Example technician account
    # Username: tech2, Password: tech123
    tech2:
      email: tech2@arrowsystems.com
      name: Jane Doe
      password: 3d8e577bddb17db339eae0b3d9bcf78f62f8b7b9c8e34ca7eb7e9b8d8e9e5a94
      salt: arrow_secure_2024
      role: technician

# Session configuration
cookie:
  name: duraflex_auth
  key: duraflex_secret_key_change_in_production
  expiry_days: 30

# Security settings
preauthorized:
  emails:
    - admin@arrowsystems.com
    - tech@arrowsystems.com

