# User Authentication Configuration
# Passwords are hashed with SHA-256
# To generate a new user:
#   1. Use Python: hashlib.sha256(("password" + "salt").encode()).hexdigest()
#   2. Or use the admin panel (coming soon)

credentials:
  usernames:
    # Default admin account
    # Username: admin, Password: admin123
    admin:
      email: admin@arrowsystems.com
      name: Administrator
      password: be61085957883d7703537a896fd6e0066622f83a890456974b8f17e81c7c9153
      salt: arrow_secure_2024
      role: admin
      
    # Example technician account
    # Username: tech1, Password: tech123
    tech1:
      email: tech1@arrowsystems.com
      name: John Smith
      password: 9d54a9e19a5abcb72e22c7c73a31d5d20297d97136e4bbb025c50407c423668d
      salt: arrow_secure_2024
      role: technician
      
    # Example technician account
    # Username: tech2, Password: tech123
    tech2:
      email: tech2@arrowsystems.com
      name: Jane Doe
      password: 9d54a9e19a5abcb72e22c7c73a31d5d20297d97136e4bbb025c50407c423668d
      salt: arrow_secure_2024
      role: technician

# Session configuration
cookie:
  name: duraflex_auth
  key: duraflex_secret_key_change_in_production
  expiry_days: 30

# Security settings
preauthorized:
  emails:
    - admin@arrowsystems.com
    - tech@arrowsystems.com

