# Streamlit Secrets Configuration
# DO NOT commit this file to version control in production!
# Add .streamlit/secrets.toml to .gitignore

# Authentication secrets
[auth]
cookie_key = "duraflex_secret_key_change_in_production"
session_timeout_hours = 24

# Database (if needed in future)
# [database]
# host = "localhost"
# port = 5432
# database = "duraflex_db"
# username = "admin"
# password = "change_me"

# API Keys (if needed for future integrations)
# [api]
# openai_key = "sk-..."
# huggingface_token = "hf_..."

